# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 - main

variables:
  uiSource: 'src'
  uiBuild: '$(uiSource)/build'
pool:
  vmImage: ubuntu-latest
  name: Movies
  demands: Agent.Name -equals AgentEsteban

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'docker build -t movies .'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'